/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ProtectedChatRouteImport } from './routes/_protected/chat'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedChatIndexRouteImport } from './routes/_protected/chat/index'
import { Route as ProtectedChatThreadIdRouteImport } from './routes/_protected/chat/$threadId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedChatRoute,
} as any)
const ProtectedChatThreadIdRoute = ProtectedChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ProtectedChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ProtectedChatRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/chat/': typeof ProtectedChatIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/chat': typeof ProtectedChatIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/chat': typeof ProtectedChatRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_protected/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/auth'
    | '/chat/$threadId'
    | '/chat/'
    | '/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chat/$threadId' | '/chat' | '/profile' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/chat'
    | '/auth/'
    | '/_protected/chat/$threadId'
    | '/_protected/chat/'
    | '/_protected/profile/'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/chat/$threadId': {
      id: '/_protected/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ProtectedChatThreadIdRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedChatRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/_protected' {
  const createFileRoute: CreateFileRoute<
    '/_protected',
    FileRoutesByPath['/_protected']['parentRoute'],
    FileRoutesByPath['/_protected']['id'],
    FileRoutesByPath['/_protected']['path'],
    FileRoutesByPath['/_protected']['fullPath']
  >
}
declare module './routes/_protected/chat' {
  const createFileRoute: CreateFileRoute<
    '/_protected/chat',
    FileRoutesByPath['/_protected/chat']['parentRoute'],
    FileRoutesByPath['/_protected/chat']['id'],
    FileRoutesByPath['/_protected/chat']['path'],
    FileRoutesByPath['/_protected/chat']['fullPath']
  >
}
declare module './routes/auth/index' {
  const createFileRoute: CreateFileRoute<
    '/auth/',
    FileRoutesByPath['/auth/']['parentRoute'],
    FileRoutesByPath['/auth/']['id'],
    FileRoutesByPath['/auth/']['path'],
    FileRoutesByPath['/auth/']['fullPath']
  >
}
declare module './routes/_protected/chat/$threadId' {
  const createFileRoute: CreateFileRoute<
    '/_protected/chat/$threadId',
    FileRoutesByPath['/_protected/chat/$threadId']['parentRoute'],
    FileRoutesByPath['/_protected/chat/$threadId']['id'],
    FileRoutesByPath['/_protected/chat/$threadId']['path'],
    FileRoutesByPath['/_protected/chat/$threadId']['fullPath']
  >
}
declare module './routes/_protected/chat/index' {
  const createFileRoute: CreateFileRoute<
    '/_protected/chat/',
    FileRoutesByPath['/_protected/chat/']['parentRoute'],
    FileRoutesByPath['/_protected/chat/']['id'],
    FileRoutesByPath['/_protected/chat/']['path'],
    FileRoutesByPath['/_protected/chat/']['fullPath']
  >
}
declare module './routes/_protected/profile/index' {
  const createFileRoute: CreateFileRoute<
    '/_protected/profile/',
    FileRoutesByPath['/_protected/profile/']['parentRoute'],
    FileRoutesByPath['/_protected/profile/']['id'],
    FileRoutesByPath['/_protected/profile/']['path'],
    FileRoutesByPath['/_protected/profile/']['fullPath']
  >
}
declare module './routes/_protected/settings/index' {
  const createFileRoute: CreateFileRoute<
    '/_protected/settings/',
    FileRoutesByPath['/_protected/settings/']['parentRoute'],
    FileRoutesByPath['/_protected/settings/']['id'],
    FileRoutesByPath['/_protected/settings/']['path'],
    FileRoutesByPath['/_protected/settings/']['fullPath']
  >
}

interface ProtectedChatRouteChildren {
  ProtectedChatThreadIdRoute: typeof ProtectedChatThreadIdRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
}

const ProtectedChatRouteChildren: ProtectedChatRouteChildren = {
  ProtectedChatThreadIdRoute: ProtectedChatThreadIdRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
}

const ProtectedChatRouteWithChildren = ProtectedChatRoute._addFileChildren(
  ProtectedChatRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedChatRoute: typeof ProtectedChatRouteWithChildren
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChatRoute: ProtectedChatRouteWithChildren,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
